title: 내 옆에 있는 사람
baseurl: ""

date_format: "%d %B %Y"

google_analytics: 'UA-62567372-1'
disqus_shortname: 'mnpk'

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
